/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.data;

import Manegement.learnAll;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import user.Connect;

/**
 *
 * @author HP
 */
public class Learn extends javax.swing.JPanel {

    private JPanel childPanel;
    private JFrame frame;

    DefaultTableModel tbn = new DefaultTableModel();
    Connect a = new Connect();
    Connection con = a.getConnection();
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    String fPath = null;
    byte[] img_DATA;

    ButtonGroup bg = new ButtonGroup();

    Timer t, time;
    int cong;

    int counter = 0;
    Boolean isIT = false;

    int point = 0;
    int count = 0;

    private String username;

    public Learn() {
        initComponents();
        //this.username = username;
        getConnection();
        loadTest();
        LoadBG();
        Topic1();
        Topic2();
        Topic3();
        loadLearn1();
        btn1.setVisible(false);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
    }

    public void Topic1() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Animal\\Rabbit.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl1.setIcon(image);
    }

    public void Topic2() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Bugs and insects\\Bee.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl2.setIcon(image);
    }

    public void Topic3() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Color\\Blue.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(150, 100, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl3.setIcon(image);
    }

    public void getConnection() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=duan1;user=sa;password=sa2008");
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("Select * from TuVung where TenChuDe not in ('Random')");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    public void loadTest() {
        try {
            rs.first();
            lblVocabulary.setText(rs.getString("TuVung"));
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void LoadBG() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Background\\18.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(696, 596, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblBg.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblPrevious = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblVocabulary = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        left = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblBg = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblImg1 = new javax.swing.JLabel();
        lblTV1 = new javax.swing.JLabel();
        sound1 = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblImg2 = new javax.swing.JLabel();
        lblTV2 = new javax.swing.JLabel();
        sound2 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblImg3 = new javax.swing.JLabel();
        lblTV3 = new javax.swing.JLabel();
        sound3 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblImg4 = new javax.swing.JLabel();
        lblTV4 = new javax.swing.JLabel();
        sound4 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblImg5 = new javax.swing.JLabel();
        lblTV5 = new javax.swing.JLabel();
        sound5 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lblImg6 = new javax.swing.JLabel();
        lblTV6 = new javax.swing.JLabel();
        sound6 = new javax.swing.JLabel();
        star6 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        lblImg7 = new javax.swing.JLabel();
        lblTV7 = new javax.swing.JLabel();
        sound7 = new javax.swing.JLabel();
        star7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btn11 = new javax.swing.JLabel();
        btn22 = new javax.swing.JLabel();
        btn33 = new javax.swing.JLabel();
        lblFlag = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, java.awt.Color.green));
        setPreferredSize(new java.awt.Dimension(1200, 830));
        setLayout(new java.awt.BorderLayout());

        top.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        top.setOpaque(false);
        top.setPreferredSize(new java.awt.Dimension(700, 200));
        top.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white));
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 230));

        lblPrevious.setBackground(new java.awt.Color(153, 255, 204));
        lblPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_64px.png"))); // NOI18N
        lblPrevious.setOpaque(true);
        lblPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPreviousMouseClicked(evt);
            }
        });

        lblNext.setBackground(new java.awt.Color(153, 255, 204));
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next_64px.png"))); // NOI18N
        lblNext.setOpaque(true);
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });

        lblVocabulary.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lblVocabulary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVocabulary, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVocabulary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        top.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        left.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 50, 30, 50));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel6.setLayout(new java.awt.GridLayout(3, 2, 30, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setAutoscrolls(true);
        lbl1.setOpaque(true);
        lbl1.setPreferredSize(new java.awt.Dimension(200, 16));
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });
        jPanel1.add(lbl1, java.awt.BorderLayout.CENTER);

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lession topic 1: Animals");
        jLabel5.setAutoscrolls(true);
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel1.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setAutoscrolls(true);
        lbl2.setOpaque(true);
        lbl2.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(lbl2, java.awt.BorderLayout.CENTER);

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lession topic 2: Bugs and insects");
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel2.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setAutoscrolls(true);
        lbl3.setOpaque(true);
        lbl3.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel3.add(lbl3, java.awt.BorderLayout.CENTER);

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lession topic 3: Colors");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(173, 50));
        jPanel3.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7);

        jPanel16.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        lblBg.setBackground(new java.awt.Color(255, 255, 255));
        lblBg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBg.setOpaque(true);
        jPanel16.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 698, 598));

        left.add(jPanel16, java.awt.BorderLayout.CENTER);

        top.add(left, java.awt.BorderLayout.CENTER);

        add(top, java.awt.BorderLayout.WEST);

        right.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        right.setPreferredSize(new java.awt.Dimension(500, 630));
        right.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setPreferredSize(new java.awt.Dimension(496, 50));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("BẮT ĐẦU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton1);

        jPanel5.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 40, 10, 40));
        jPanel10.setLayout(new java.awt.GridLayout(7, 1, 20, 10));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg1.setBackground(new java.awt.Color(255, 255, 255));
        lblImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg1.setOpaque(true);
        lblImg1.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel11.add(lblImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV1.setBackground(new java.awt.Color(254, 255, 231));
        lblTV1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV1.setOpaque(true);
        lblTV1.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel11.add(lblTV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound1.setBackground(new java.awt.Color(254, 255, 231));
        sound1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound1.setOpaque(true);
        jPanel11.add(sound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star1.setBackground(new java.awt.Color(254, 255, 231));
        star1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star1.setOpaque(true);
        jPanel11.add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg2.setBackground(new java.awt.Color(255, 255, 255));
        lblImg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg2.setOpaque(true);
        lblImg2.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel12.add(lblImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV2.setBackground(new java.awt.Color(254, 255, 231));
        lblTV2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV2.setOpaque(true);
        lblTV2.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel12.add(lblTV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound2.setBackground(new java.awt.Color(254, 255, 231));
        sound2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound2.setOpaque(true);
        jPanel12.add(sound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star2.setBackground(new java.awt.Color(254, 255, 231));
        star2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star2.setOpaque(true);
        jPanel12.add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg3.setBackground(new java.awt.Color(255, 255, 255));
        lblImg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg3.setOpaque(true);
        lblImg3.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel13.add(lblImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV3.setBackground(new java.awt.Color(254, 255, 231));
        lblTV3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV3.setOpaque(true);
        lblTV3.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel13.add(lblTV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound3.setBackground(new java.awt.Color(254, 255, 231));
        sound3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound3.setOpaque(true);
        jPanel13.add(sound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star3.setBackground(new java.awt.Color(254, 255, 231));
        star3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star3.setOpaque(true);
        jPanel13.add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg4.setBackground(new java.awt.Color(255, 255, 255));
        lblImg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg4.setOpaque(true);
        lblImg4.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel14.add(lblImg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV4.setBackground(new java.awt.Color(254, 255, 231));
        lblTV4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV4.setOpaque(true);
        lblTV4.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel14.add(lblTV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound4.setBackground(new java.awt.Color(254, 255, 231));
        sound4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound4.setOpaque(true);
        jPanel14.add(sound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star4.setBackground(new java.awt.Color(254, 255, 231));
        star4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star4.setOpaque(true);
        jPanel14.add(star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg5.setBackground(new java.awt.Color(255, 255, 255));
        lblImg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg5.setOpaque(true);
        lblImg5.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel15.add(lblImg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV5.setBackground(new java.awt.Color(254, 255, 231));
        lblTV5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV5.setOpaque(true);
        lblTV5.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel15.add(lblTV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound5.setBackground(new java.awt.Color(254, 255, 231));
        sound5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound5.setOpaque(true);
        jPanel15.add(sound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star5.setBackground(new java.awt.Color(254, 255, 231));
        star5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star5.setOpaque(true);
        jPanel15.add(star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel15);

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg6.setBackground(new java.awt.Color(255, 255, 255));
        lblImg6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg6.setOpaque(true);
        lblImg6.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel19.add(lblImg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV6.setBackground(new java.awt.Color(254, 255, 231));
        lblTV6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV6.setOpaque(true);
        lblTV6.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel19.add(lblTV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound6.setBackground(new java.awt.Color(254, 255, 231));
        sound6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound6.setOpaque(true);
        jPanel19.add(sound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star6.setBackground(new java.awt.Color(254, 255, 231));
        star6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star6.setOpaque(true);
        jPanel19.add(star6, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel19);

        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg7.setBackground(new java.awt.Color(255, 255, 255));
        lblImg7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg7.setOpaque(true);
        lblImg7.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel20.add(lblImg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, 82));

        lblTV7.setBackground(new java.awt.Color(254, 255, 231));
        lblTV7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTV7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTV7.setOpaque(true);
        lblTV7.setPreferredSize(new java.awt.Dimension(120, 16));
        jPanel20.add(lblTV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 2, 242, 82));

        sound7.setBackground(new java.awt.Color(254, 255, 231));
        sound7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sound7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/speaker.png"))); // NOI18N
        sound7.setOpaque(true);
        jPanel20.add(sound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 2, 44, 41));

        star7.setBackground(new java.awt.Color(254, 255, 231));
        star7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        star7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9004689_star_favorite_like_award_rating_icon.png"))); // NOI18N
        star7.setOpaque(true);
        jPanel20.add(star7, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 43, 44, 41));

        jPanel10.add(jPanel20);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(472, 70));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1814083_arrow_left_icon.png"))); // NOI18N
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPreviousMousePressed(evt);
            }
        });
        jPanel9.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 5, -1, -1));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/352531_looks_one_1_icon.png"))); // NOI18N
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });
        jPanel9.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 5, -1, -1));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/352532_looks_2_two_icon.png"))); // NOI18N
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn2KeyReleased(evt);
            }
        });
        jPanel9.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 5, -1, -1));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/352526_3_looks_icon.png"))); // NOI18N
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
        });
        jPanel9.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 5, -1, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1814085_arrow_forward_next_right_icon.png"))); // NOI18N
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextMousePressed(evt);
            }
        });
        jPanel9.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 5, -1, -1));

        btn11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/352531_looks_one_1_icon (1).png"))); // NOI18N
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn11MousePressed(evt);
            }
        });
        jPanel9.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 5, -1, -1));

        btn22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/352532_looks_2_two_icon (1).png"))); // NOI18N
        btn22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn22MousePressed(evt);
            }
        });
        jPanel9.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 5, -1, -1));

        btn33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/352526_3_looks_icon (1).png"))); // NOI18N
        btn33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn33MousePressed(evt);
            }
        });
        jPanel9.add(btn33, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 5, -1, -1));

        lblFlag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFlag.setText("Pages : 1");
        lblFlag.setPreferredSize(new java.awt.Dimension(65, 32));
        jPanel9.add(lblFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 5, -1, -1));

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        right.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(right, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        try {
            if (!rs.isLast()) {
                rs.next();
                lblVocabulary.setText(rs.getString(2));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPreviousMouseClicked
        try {
            if (!rs.isFirst()) {
                rs.previous();
                lblVocabulary.setText(rs.getString(2));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblPreviousMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        learnAll q = new learnAll();
        q.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        learnAll q = new learnAll();
        q.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_lbl1MouseClicked

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextMouseClicked

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
        mouse1();
        if (flag == 1) {
            loadLearn1();
        }
        if (flag == 2) {
            loadLearn2();
        }
    }//GEN-LAST:event_btn1MousePressed

    private void mouse1() {
        btn1.setVisible(false);
        btn11.setVisible(true);
        btn2.setVisible(true);
        btn22.setVisible(false);
        btn3.setVisible(true);
        btn33.setVisible(false);
    }

    private void btn11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MousePressed
        mouse11();
    }//GEN-LAST:event_btn11MousePressed

    private void mouse11() {
        btn1.setEnabled(true);
        btn1.setVisible(true);
        btn11.setVisible(false);
        btn2.setVisible(true);
        btn22.setVisible(false);
        btn3.setVisible(true);
        btn33.setVisible(false);
    }

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        mouse2();
        if (flag == 1) {
            loadLearn2();
        }
        if (flag == 2) {
            loadLearn5();
        }

    }//GEN-LAST:event_btn2MousePressed

    private void mouse2() {
        btn1.setVisible(true);
        btn11.setVisible(false);
        btn2.setVisible(false);
        btn22.setVisible(true);
        btn3.setVisible(true);
        btn33.setVisible(false);
    }

    private void btn22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn22MousePressed
        mouse22();
    }//GEN-LAST:event_btn22MousePressed

    private void mouse22() {
        btn2.setEnabled(true);
        btn1.setVisible(true);
        btn11.setVisible(false);
        btn2.setVisible(true);
        btn22.setVisible(false);
        btn3.setVisible(true);
        btn33.setVisible(false);
    }

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
        mouse3();
        if (flag == 1) {
            loadLearn3();
        }
        if (flag == 2) {
            loadLearn6();
        }
    }//GEN-LAST:event_btn3MousePressed

    private void mouse3() {
        btn1.setVisible(true);
        btn11.setVisible(false);
        btn2.setVisible(true);
        btn22.setVisible(false);
        btn3.setVisible(false);
        btn33.setVisible(true);
    }

    private void btn33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn33MousePressed
        mouse33();
    }//GEN-LAST:event_btn33MousePressed

    private void mouse33() {
        btn3.setEnabled(true);
        btn1.setVisible(true);
        btn11.setVisible(false);
        btn2.setVisible(true);
        btn22.setVisible(false);
        btn3.setVisible(true);
        btn33.setVisible(false);
    }

    private void btn2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyReleased
        loadLearn2();
    }//GEN-LAST:event_btn2KeyReleased

    int flag = 1;
    private void btnNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMousePressed
        btnNext.setEnabled(false);
        btnPrevious.setEnabled(true);
        if (flag >= 1) {
            flag += 1;
            lblFlag.setText("Pages : " + flag);
        }
    }//GEN-LAST:event_btnNextMousePressed

    private void btnPreviousMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMousePressed
        btnNext.setEnabled(true);
        btnPrevious.setEnabled(false);
        if (flag > 1) {
            flag -= 1;
            lblFlag.setText("Pages : " + flag);
        }
    }//GEN-LAST:event_btnPreviousMousePressed

    public void tv001() {
        try {
            rs.first();
            lblTV1.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 35, Image.SCALE_SMOOTH));
            lblImg1.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void tv002() {
        try {
            rs.next();
            lblTV2.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 35, Image.SCALE_SMOOTH));
            lblImg2.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void tv003() {
        try {
            rs.next();
            lblTV3.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 40, Image.SCALE_SMOOTH));
            lblImg3.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void tv004() {
        try {
            rs.next();
            lblTV4.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 40, Image.SCALE_SMOOTH));
            lblImg4.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void tv005() {
        try {
            rs.next();
            lblTV5.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 40, Image.SCALE_SMOOTH));
            lblImg5.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void tv006() {
        try {
            rs.next();
            lblTV6.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 40, Image.SCALE_SMOOTH));
            lblImg6.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void tv007() {
        try {
            rs.next();
            lblTV7.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 40, Image.SCALE_SMOOTH));
            lblImg7.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void tv008() {
        try {
            rs.next();
            lblTV1.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(70, 40, Image.SCALE_SMOOTH));
            lblImg1.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    private void loadlearn() {
        tv002();
        tv003();
        tv004();
        tv005();
        tv006();
        tv007();
    }

    public void loadLearn1() {
        tv001();
        loadlearn();
    }

    public void loadLearn2() {
        tv008();
        loadlearn();
    }

    public void loadLearn3() {
        tv008();
        loadlearn();
    }

    public void loadLearn4() {
        tv008();
        loadlearn();
    }

    public void loadLearn5() {
        tv008();
        loadlearn();
    }

    public void loadLearn6() {
        tv008();
        loadlearn();
    }

    public void loadLearn7() {
        tv008();
        loadlearn();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn11;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel btn22;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btn33;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnPrevious;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblBg;
    private javax.swing.JLabel lblFlag;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg4;
    private javax.swing.JLabel lblImg5;
    private javax.swing.JLabel lblImg6;
    private javax.swing.JLabel lblImg7;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrevious;
    private javax.swing.JLabel lblTV1;
    private javax.swing.JLabel lblTV2;
    private javax.swing.JLabel lblTV3;
    private javax.swing.JLabel lblTV4;
    private javax.swing.JLabel lblTV5;
    private javax.swing.JLabel lblTV6;
    private javax.swing.JLabel lblTV7;
    private javax.swing.JLabel lblVocabulary;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    private javax.swing.JLabel sound1;
    private javax.swing.JLabel sound2;
    private javax.swing.JLabel sound3;
    private javax.swing.JLabel sound4;
    private javax.swing.JLabel sound5;
    private javax.swing.JLabel sound6;
    private javax.swing.JLabel sound7;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    private javax.swing.JLabel star6;
    private javax.swing.JLabel star7;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
