/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.topicTNDT;

import Manegement.TopicTest.testD1;
import Manegement.TopicTest.testD2;
import Manegement.TopicTest.testK1;
import Manegement.TopicTest.testK2;
import Manegement.TopicTest.testM1;
import Manegement.TopicTest.testM2;
import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ChuDeQuiz extends javax.swing.JPanel {

    private JPanel childPanel;
    private JFrame frame;

    public ChuDeQuiz() {
        initComponents();
        loadListTopic();
        lession1.setEnabled(false);
        lession2.setEnabled(false);
        lession3.setEnabled(false);
        cbxCHTN.setEnabled(false);
        cbxCHDT.setEnabled(false);
        cbxAnimals.setEnabled(false);
        cbxBugsAndInsects.setEnabled(false);
        cbxColors.setEnabled(false);
        checkboxTopic();
    }

    public void loadListTopic() {
        Topic1();
        Topic2();
        Topic3();
    }

    public void Topic1() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Animal\\Cat.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(248, 158, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic1.setIcon(image);
    }

    public void Topic2() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Bugs and insects\\Bee.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(248, 158, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic2.setIcon(image);
    }

    public void Topic3() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Color\\Grey.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(248, 158, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic3.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        ListTopic = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AnimalTopic = new javax.swing.JPanel();
        lession1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblImgTopic1 = new javax.swing.JLabel();
        lession2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lblImgTopic2 = new javax.swing.JLabel();
        lession3 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lblImgTopic3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbxDe = new javax.swing.JCheckBox();
        cbxTB = new javax.swing.JCheckBox();
        cbxKho = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        testAll = new javax.swing.JPanel();
        cbxCHTN = new javax.swing.JCheckBox();
        cbxCHDT = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        cbxAnimals = new javax.swing.JCheckBox();
        cbxBugsAndInsects = new javax.swing.JCheckBox();
        cbxColors = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102)));
        setPreferredSize(new java.awt.Dimension(1200, 830));
        setLayout(new java.awt.BorderLayout());

        ListTopic.setBackground(new java.awt.Color(255, 255, 255));
        ListTopic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListTopic.setPreferredSize(new java.awt.Dimension(1200, 630));
        ListTopic.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 50, 30, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 20));

        AnimalTopic.setBackground(new java.awt.Color(240, 248, 255));
        AnimalTopic.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true), javax.swing.BorderFactory.createTitledBorder(null, "LIST TEST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20)))); // NOI18N
        AnimalTopic.setAutoscrolls(true);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 20);
        flowLayout1.setAlignOnBaseline(true);
        AnimalTopic.setLayout(flowLayout1);

        lession1.setBackground(new java.awt.Color(255, 255, 255));
        lession1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lession1.setPreferredSize(new java.awt.Dimension(250, 200));
        lession1.setLayout(new java.awt.BorderLayout());

        lbl1.setBackground(new java.awt.Color(0, 255, 153));
        lbl1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Lession Topic 1");
        lbl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl1.setOpaque(true);
        lbl1.setPreferredSize(new java.awt.Dimension(274, 40));
        lession1.add(lbl1, java.awt.BorderLayout.PAGE_START);

        lblImgTopic1.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic1MouseClicked(evt);
            }
        });
        lession1.add(lblImgTopic1, java.awt.BorderLayout.CENTER);

        AnimalTopic.add(lession1);

        lession2.setBackground(new java.awt.Color(255, 255, 255));
        lession2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lession2.setPreferredSize(new java.awt.Dimension(250, 200));
        lession2.setLayout(new java.awt.BorderLayout());

        lbl2.setBackground(new java.awt.Color(0, 255, 153));
        lbl2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Lession Topic 2 ");
        lbl2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl2.setOpaque(true);
        lbl2.setPreferredSize(new java.awt.Dimension(274, 40));
        lession2.add(lbl2, java.awt.BorderLayout.PAGE_START);

        lblImgTopic2.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic2MouseClicked(evt);
            }
        });
        lession2.add(lblImgTopic2, java.awt.BorderLayout.CENTER);

        AnimalTopic.add(lession2);

        lession3.setBackground(new java.awt.Color(255, 255, 255));
        lession3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lession3.setPreferredSize(new java.awt.Dimension(250, 200));
        lession3.setLayout(new java.awt.BorderLayout());

        lbl3.setBackground(new java.awt.Color(0, 255, 153));
        lbl3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Lession Topic 3");
        lbl3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl3.setOpaque(true);
        lbl3.setPreferredSize(new java.awt.Dimension(274, 40));
        lession3.add(lbl3, java.awt.BorderLayout.PAGE_START);

        lblImgTopic3.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic3MouseClicked(evt);
            }
        });
        lession3.add(lblImgTopic3, java.awt.BorderLayout.CENTER);

        AnimalTopic.add(lession3);

        jPanel3.add(AnimalTopic);

        ListTopic.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ListTopic.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        add(ListTopic, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(1286, 60));
        Header.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("KIỂM TRA TỪ VỰNG THEO CHỦ ĐỀ");
        jLabel5.setOpaque(true);
        Header.add(jLabel5);

        jPanel1.add(Header, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(240, 248, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(1194, 146));

        buttonGroup1.add(cbxDe);
        cbxDe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxDe.setText("Cấp độ dễ");
        cbxDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbxTB);
        cbxTB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxTB.setText("Cấp độ trung bình");
        cbxTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTBActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbxKho);
        cbxKho.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxKho.setText("Cấp độ khó");
        cbxKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Chọn cấp độ bài kiểm tra");

        testAll.setBackground(new java.awt.Color(255, 255, 204));
        testAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cbxCHTN.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(cbxCHTN);
        cbxCHTN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxCHTN.setText("Câu hỏi trắc nghiệm");
        cbxCHTN.setAutoscrolls(true);
        cbxCHTN.setBorderPainted(true);
        cbxCHTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCHTNActionPerformed(evt);
            }
        });

        cbxCHDT.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(cbxCHDT);
        cbxCHDT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxCHDT.setText("Câu hỏi điền từ");
        cbxCHDT.setAutoscrolls(true);
        cbxCHDT.setBorderPainted(true);
        cbxCHDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCHDTActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cbxAnimals.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(cbxAnimals);
        cbxAnimals.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxAnimals.setText("Animals");
        cbxAnimals.setAutoscrolls(true);
        cbxAnimals.setBorderPainted(true);

        cbxBugsAndInsects.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(cbxBugsAndInsects);
        cbxBugsAndInsects.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxBugsAndInsects.setText("Bugs and insects");
        cbxBugsAndInsects.setAutoscrolls(true);
        cbxBugsAndInsects.setBorderPainted(true);

        cbxColors.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(cbxColors);
        cbxColors.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxColors.setText("Colors");
        cbxColors.setAutoscrolls(true);
        cbxColors.setBorderPainted(true);

        javax.swing.GroupLayout testAllLayout = new javax.swing.GroupLayout(testAll);
        testAll.setLayout(testAllLayout);
        testAllLayout.setHorizontalGroup(
            testAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testAllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxCHTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxCHDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxBugsAndInsects, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxColors, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        testAllLayout.setVerticalGroup(
            testAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(testAllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testAllLayout.createSequentialGroup()
                        .addComponent(cbxCHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCHDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(testAllLayout.createSequentialGroup()
                        .addGroup(testAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxBugsAndInsects, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxColors, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbxDe)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTB)
                        .addGap(18, 18, 18)
                        .addComponent(cbxKho))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(testAll, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxKho)
                            .addComponent(cbxDe)
                            .addComponent(cbxTB))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(testAll, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    public void checkboxQuestion() {
        if (cbxDe.isSelected() == true || cbxTB.isSelected() == true || cbxKho.isSelected() == true) {
            cbxCHTN.setEnabled(true);
            cbxCHDT.setEnabled(true);
        }
    }

    public void checkboxTopic() {
        if (cbxCHTN.isSelected() == true || cbxCHDT.isSelected() == true) {
            cbxAnimals.setEnabled(true);
            cbxBugsAndInsects.setEnabled(true);
            cbxColors.setEnabled(true);
        }
    }

    private void cbxDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeActionPerformed
        checkboxQuestion();
    }//GEN-LAST:event_cbxDeActionPerformed

    private void cbxTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTBActionPerformed
        checkboxQuestion();
    }//GEN-LAST:event_cbxTBActionPerformed

    private void cbxKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhoActionPerformed
        checkboxQuestion();
    }//GEN-LAST:event_cbxKhoActionPerformed

    private void cbxCHTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCHTNActionPerformed
        checkboxTopic();
    }//GEN-LAST:event_cbxCHTNActionPerformed

    private void cbxCHDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCHDTActionPerformed
        checkboxTopic();
    }//GEN-LAST:event_cbxCHDTActionPerformed

    private void lblImgTopic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic1MouseClicked
        if (cbxDe.isSelected() == false && cbxKho.isSelected() == false && cbxTB.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Xin hãy chọn cấp độ!");
        } else if (cbxDe.isSelected() == true || cbxKho.isSelected() == true || cbxTB.isSelected() == true) {
            if (cbxCHTN.isSelected() == false && cbxCHDT.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "Xin hãy chọn loại câu hỏi!");
            } else if (cbxCHTN.isSelected() == true || cbxCHDT.isSelected() == true) {
                if (cbxAnimals.isSelected() == false && cbxBugsAndInsects.isSelected() == false && cbxColors.isSelected() == false) {
                    JOptionPane.showMessageDialog(this, "Xin hãy chọn chủ đề!");
                } else {
                    if (cbxDe.isSelected() == true && cbxCHTN.isSelected() == true && cbxAnimals.isSelected() == true) {
                        try {
                            lbl1.setBackground(Color.orange);
                            Thread.sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(ChuDeQuiz.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        testD1 q = new testD1();
                        q.setVisible(true);
                    } else if (cbxTB.isSelected() == true && cbxCHTN.isSelected() == true && cbxAnimals.isSelected() == true) {
                        testM1 q = new testM1();
                        q.setVisible(true);
                    } else if (cbxKho.isSelected() == true && cbxCHTN.isSelected() == true && cbxAnimals.isSelected() == true) {
                        testK1 q = new testK1();
                        q.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_lblImgTopic1MouseClicked

    private void lblImgTopic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic2MouseClicked
        if (cbxDe.isSelected() == false && cbxKho.isSelected() == false && cbxTB.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Xin hãy chọn cấp độ!");
        } else if (cbxDe.isSelected() == true || cbxKho.isSelected() == true || cbxTB.isSelected() == true) {
            if (cbxCHTN.isSelected() == false && cbxCHDT.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "Xin hãy chọn loại câu hỏi!");
            } else if (cbxCHTN.isSelected() == true || cbxCHDT.isSelected() == true) {
                if (cbxBugsAndInsects.isSelected() == false && cbxBugsAndInsects.isSelected() == false && cbxColors.isSelected() == false) {
                    JOptionPane.showMessageDialog(this, "Xin hãy chọn chủ đề!");
                } else {
                    if (cbxDe.isSelected() == true && cbxCHTN.isSelected() == true && cbxBugsAndInsects.isSelected() == true) {
                        try {
                            lbl1.setBackground(Color.orange);
                            Thread.sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(ChuDeQuiz.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        testD2 q = new testD2();
                        q.setVisible(true);
                    } else if (cbxTB.isSelected() == true && cbxCHTN.isSelected() == true && cbxBugsAndInsects.isSelected() == true) {
                        testM2 q = new testM2();
                        q.setVisible(true);
                    } else if (cbxKho.isSelected() == true && cbxCHTN.isSelected() == true && cbxBugsAndInsects.isSelected() == true) {
                        testK2 q = new testK2();
                        q.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_lblImgTopic2MouseClicked

    private void lblImgTopic3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImgTopic3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnimalTopic;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel ListTopic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbxAnimals;
    private javax.swing.JCheckBox cbxBugsAndInsects;
    private javax.swing.JCheckBox cbxCHDT;
    private javax.swing.JCheckBox cbxCHTN;
    private javax.swing.JCheckBox cbxColors;
    private javax.swing.JCheckBox cbxDe;
    private javax.swing.JCheckBox cbxKho;
    private javax.swing.JCheckBox cbxTB;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblImgTopic1;
    private javax.swing.JLabel lblImgTopic2;
    private javax.swing.JLabel lblImgTopic3;
    private javax.swing.JPanel lession1;
    private javax.swing.JPanel lession2;
    private javax.swing.JPanel lession3;
    private javax.swing.JPanel testAll;
    // End of variables declaration//GEN-END:variables
}
